// <auto-generated />
using csharp_dotnet_core_web_api_hotel_listing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace csharp_dotnet_core_web_api_hotel_listing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210717121833_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("csharp_dotnet_core_web_api_hotel_listing.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 3,
                            Code = "FR",
                            Name = "France"
                        });
                });

            modelBuilder.Entity("csharp_dotnet_core_web_api_hotel_listing.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bangalore, India",
                            CountryId = 1,
                            Name = "Indian Coffee House",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Sydney, Australia",
                            CountryId = 3,
                            Name = "Australian Hut",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Address = "Paris, France",
                            CountryId = 2,
                            Name = "Paris Corner",
                            Rating = 3.5
                        });
                });

            modelBuilder.Entity("csharp_dotnet_core_web_api_hotel_listing.Data.Hotel", b =>
                {
                    b.HasOne("csharp_dotnet_core_web_api_hotel_listing.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
